DROP TABLE schedules IF EXISTS;
DROP TABLE users_talks IF EXISTS;
DROP TABLE talk IF EXISTS;
DROP TABLE room IF EXISTS;
DROP TABLE user IF EXISTS;

CREATE TABLE room
(
    room_id         INTEGER   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_name        VARCHAR(255)   NOT NULL UNIQUE
);


CREATE TABLE user
(
    user_id          INTEGER   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username         VARCHAR(255)   NOT NULL UNIQUE,
    password         VARCHAR(255)   NOT NULL,
    role             VARCHAR(32)    NOT NULL
);


CREATE TABLE talk
(
    talk_id         INTEGER   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    talk_name        VARCHAR(255)   NOT NULL --,
--    schedule_id     INTEGER,
--    FOREIGN KEY (schedule_id) REFERENCES schedule (id) ON DELETE CASCADE
);

CREATE TABLE users_talks
(
    user_id         INTEGER        NOT NULL,
    talk_id         INTEGER        NOT NULL,
    CONSTRAINT users_talks_idx UNIQUE (user_id, talk_id),
    FOREIGN KEY (user_id) REFERENCES user (user_id) ON DELETE CASCADE,
    FOREIGN KEY (talk_id) REFERENCES talk (talk_id) ON DELETE CASCADE
);

CREATE TABLE schedule
(
    schedule_id      INTEGER   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_start       DATETIME      NOT NULL,
    date_end         DATETIME      NOT NULL,
    room_id          INTEGER       NOT NULL,
    talk_id          INTEGER       NOT NULL,
    FOREIGN KEY (room_id) REFERENCES room (room_id) ON DELETE CASCADE,
    FOREIGN KEY (talk_id) REFERENCES talk (talk_id) ON DELETE CASCADE
);